# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/HomeWork/03"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/HomeWork/03/CMakeFiles" "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/HomeWork/03//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/HomeWork/03/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imNumbers

# Build rule for target.
imNumbers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imNumbers
.PHONY : imNumbers

# fast build rule for target.
imNumbers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/build
.PHONY : imNumbers/fast

#=============================================================================
# Target rules for targets named Google_Tests_run_imNumbers

# Build rule for target.
Google_Tests_run_imNumbers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Google_Tests_run_imNumbers
.PHONY : Google_Tests_run_imNumbers

# fast build rule for target.
Google_Tests_run_imNumbers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/build
.PHONY : Google_Tests_run_imNumbers/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make" "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build"
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make" "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build"
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make" "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googletest/CMakeFiles/gtest.dir/build"
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make" "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/C++/CppTeaching/homeWork/03/_deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build"
.PHONY : gtest_main/fast

imNumberss/imNumbers.o: imNumberss/imNumbers.cpp.o
.PHONY : imNumberss/imNumbers.o

# target to build an object file
imNumberss/imNumbers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/imNumberss/imNumbers.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/imNumberss/imNumbers.cpp.o
.PHONY : imNumberss/imNumbers.cpp.o

imNumberss/imNumbers.i: imNumberss/imNumbers.cpp.i
.PHONY : imNumberss/imNumbers.i

# target to preprocess a source file
imNumberss/imNumbers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/imNumberss/imNumbers.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/imNumberss/imNumbers.cpp.i
.PHONY : imNumberss/imNumbers.cpp.i

imNumberss/imNumbers.s: imNumberss/imNumbers.cpp.s
.PHONY : imNumberss/imNumbers.s

# target to generate assembly for a file
imNumberss/imNumbers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/imNumberss/imNumbers.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/imNumberss/imNumbers.cpp.s
.PHONY : imNumberss/imNumbers.cpp.s

imNumberss/main.o: imNumberss/main.cpp.o
.PHONY : imNumberss/main.o

# target to build an object file
imNumberss/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/imNumberss/main.cpp.o
.PHONY : imNumberss/main.cpp.o

imNumberss/main.i: imNumberss/main.cpp.i
.PHONY : imNumberss/main.i

# target to preprocess a source file
imNumberss/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/imNumberss/main.cpp.i
.PHONY : imNumberss/main.cpp.i

imNumberss/main.s: imNumberss/main.cpp.s
.PHONY : imNumberss/main.s

# target to generate assembly for a file
imNumberss/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imNumbers.dir/build.make CMakeFiles/imNumbers.dir/imNumberss/main.cpp.s
.PHONY : imNumberss/main.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

tests/test_imNumbers.o: tests/test_imNumbers.cpp.o
.PHONY : tests/test_imNumbers.o

# target to build an object file
tests/test_imNumbers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/tests/test_imNumbers.cpp.o
.PHONY : tests/test_imNumbers.cpp.o

tests/test_imNumbers.i: tests/test_imNumbers.cpp.i
.PHONY : tests/test_imNumbers.i

# target to preprocess a source file
tests/test_imNumbers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/tests/test_imNumbers.cpp.i
.PHONY : tests/test_imNumbers.cpp.i

tests/test_imNumbers.s: tests/test_imNumbers.cpp.s
.PHONY : tests/test_imNumbers.s

# target to generate assembly for a file
tests/test_imNumbers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_Tests_run_imNumbers.dir/build.make CMakeFiles/Google_Tests_run_imNumbers.dir/tests/test_imNumbers.cpp.s
.PHONY : tests/test_imNumbers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Google_Tests_run_imNumbers"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... imNumbers"
	@echo "... imNumberss/imNumbers.o"
	@echo "... imNumberss/imNumbers.i"
	@echo "... imNumberss/imNumbers.s"
	@echo "... imNumberss/main.o"
	@echo "... imNumberss/main.i"
	@echo "... imNumberss/main.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
	@echo "... tests/test_imNumbers.o"
	@echo "... tests/test_imNumbers.i"
	@echo "... tests/test_imNumbers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

